
version: "3"

services:
    anki-container:
        image: kuklinistvan/anki-sync-server:latest
        container_name: anki-container
        restart: always
        ports:
          - "10.8.0.1:27701:27701"
        volumes:
          - anki_data:/app/data
