
version: "3"

services:
    anki-container:
        image: kuklinistvan/anki-sync-server:latest
        container_name: anki-container
        restart: always
        ports:
          - "127.0.0.1:27701:27701"
        volumes:
          - ./docker_data/anki_sync:/app/data
