
version: "3"

services:
    nextcloud_continer:
        image: nextcloud:latest
        container_name: nextcloud-container
        restart: always
        ports:
          - "10.8.0.1:8080:80"
        volumes:
          - nextcloud_data:/var/www/html
