
version: "3"

services:
    nextcloud_continer:
        image: nextcloud:latest
        container_name: nextcloud-container
        restart: always
        ports:
          - "127.0.0.1:8080:80"
        volumes:
          - ./.docker_data/nextcloud:/var/www/html
