[powershell.files]
".config/windows/powershell.ps1" = "~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1"
".config/windows/powershell.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
